spring:
  application:
    name: contribot
github:
  token: ${GITHUB_TOKEN}
  issueSearch:
    pageSize: 100
    query:
      template: is:issue is:open label:"%s" language:%s sort:created-desc created:>=%s
      label: good first issue
      language: Java
    job:
      executionFilePath: data/issuesearch/job-execution.json
      firstRunDeltaHours: 4