spring:
  application:
    name: contribot
github:
  token: ${GITHUB_TOKEN}
  issue-search:
    page-size: 50
    query:
      qualifiers:
        - is:issue
        - is:open
        - label:"good first issue"
        - language:Java
    job:
      execution-file: data/job/issuesearch/state.json
      initial-lookback-hours: 4